name: smartfitness
description: SMART FITNESS — white-label HR attendance app shell.
publish_to: none
version: 1.0.7+9

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hr_core:
    path: ../../packages/hr_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
